name: celebrimbor
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - bakta>=1.9
  - mmseqs2
  - pandas
  - biopython
  - checkm-genome
  - snakemake
  - panaroo
  - rust
